env:
  global:
    - CC_TEST_REPORTER_ID=9b22cf1db3e49bf488c74c187c8103b2bdb98b9947cee0efd018d6efbbf756ea
language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
after_success: 
  # - NODE_ENV=test istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
  - "npm test"
  # - "npm install babel-core babel-preset-es2015 mocha nyc"
  # - "npm run testcover"
  # - "npm run coverage"
before_script:
  - npm install nyc
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - npm test
  # - nyc report --reporter=lcov --require babel-core/register npm test --exit
  # - nyc report --reporter=lcov > ./node_modules/coveralls/bin/coveralls.js

after_script:
  - npm run coverage
  # - nyc --reporter=lcov --reporter=text mocha test/*.js
  # - NODE_ENV=istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverag
  - ./cc-test-reporter after-build --debug -t lcov upload-coverage --exit-code $TRAVIS_TEST_RESULT

notifications:
  email: false