language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
after_success: 
  - "npm install babel-core babel-preset-es2015 mocha nyc"
  - "npm run testcover"
before_script:
  - "npm install babel-core babel-preset-es2015 mocha nyc"
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - nyc --reporter=lcov npm run testcover

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

notifications:
  email: false